// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertAuditLogsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Detail       []byte      `json:"detail"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)::bigint AS count FROM audit_logs
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::uuid IS NULL OR bot_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::text IS NULL OR resource_type = $4)
`

type CountAuditLogsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	Action       pgtype.Text `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.UserID,
		arg.BotID,
		arg.Action,
		arg.ResourceType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (user_id, bot_id, action, resource_type, resource_id, detail, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, bot_id, action, resource_type, resource_id, detail, ip_address, user_agent, created_at
`

type InsertAuditLogParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Detail       []byte      `json:"detail"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.BotID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Detail,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BotID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Detail,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, bot_id, action, resource_type, resource_id, detail, ip_address, user_agent, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::uuid IS NULL OR bot_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::text IS NULL OR resource_type = $4)
ORDER BY created_at DESC
LIMIT $6
OFFSET $5
`

type ListAuditLogsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	Action       pgtype.Text `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
	PageOffset   int32       `json:"page_offset"`
	PageSize     int32       `json:"page_size"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.UserID,
		arg.BotID,
		arg.Action,
		arg.ResourceType,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BotID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
