// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBotPermission = `-- name: DeleteBotPermission :exec
DELETE FROM bot_permissions WHERE id = $1
`

func (q *Queries) DeleteBotPermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotPermission, id)
	return err
}

const deleteBotPermissionsByBot = `-- name: DeleteBotPermissionsByBot :exec
DELETE FROM bot_permissions WHERE bot_id = $1
`

func (q *Queries) DeleteBotPermissionsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotPermissionsByBot, botID)
	return err
}

const getBotPermission = `-- name: GetBotPermission :one
SELECT id, bot_id, role, resource, action, allowed, created_at FROM bot_permissions
WHERE bot_id = $1 AND role = $2 AND resource = $3 AND action = $4
`

type GetBotPermissionParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	Role     string      `json:"role"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
}

func (q *Queries) GetBotPermission(ctx context.Context, arg GetBotPermissionParams) (BotPermission, error) {
	row := q.db.QueryRow(ctx, getBotPermission,
		arg.BotID,
		arg.Role,
		arg.Resource,
		arg.Action,
	)
	var i BotPermission
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Role,
		&i.Resource,
		&i.Action,
		&i.Allowed,
		&i.CreatedAt,
	)
	return i, err
}

const listBotPermissions = `-- name: ListBotPermissions :many
SELECT id, bot_id, role, resource, action, allowed, created_at FROM bot_permissions
WHERE bot_id = $1
ORDER BY role, resource, action
`

func (q *Queries) ListBotPermissions(ctx context.Context, botID pgtype.UUID) ([]BotPermission, error) {
	rows, err := q.db.Query(ctx, listBotPermissions, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPermission
	for rows.Next() {
		var i BotPermission
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Role,
			&i.Resource,
			&i.Action,
			&i.Allowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotPermission = `-- name: UpsertBotPermission :one
INSERT INTO bot_permissions (bot_id, role, resource, action, allowed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (bot_id, role, resource, action) DO UPDATE SET allowed = $5
RETURNING id, bot_id, role, resource, action, allowed, created_at
`

type UpsertBotPermissionParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	Role     string      `json:"role"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
	Allowed  bool        `json:"allowed"`
}

func (q *Queries) UpsertBotPermission(ctx context.Context, arg UpsertBotPermissionParams) (BotPermission, error) {
	row := q.db.QueryRow(ctx, upsertBotPermission,
		arg.BotID,
		arg.Role,
		arg.Resource,
		arg.Action,
		arg.Allowed,
	)
	var i BotPermission
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Role,
		&i.Resource,
		&i.Action,
		&i.Allowed,
		&i.CreatedAt,
	)
	return i, err
}
