// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cockpit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cockpitAggregateByDateRange = `-- name: CockpitAggregateByDateRange :one
SELECT
    COUNT(*)::bigint AS total_reports,
    COALESCE(SUM(total_estimated_saved_hours), 0)::numeric AS total_saved_hours,
    COALESCE(SUM(total_ai_time_minutes), 0)::bigint AS total_ai_minutes,
    COALESCE(SUM(innovation_count), 0)::bigint AS total_innovations,
    COALESCE(AVG(efficiency_multiplier), 0)::numeric AS avg_efficiency
FROM cockpit_daily_reports
WHERE bot_id = $1
  AND report_date >= $2
  AND report_date <= $3
`

type CockpitAggregateByDateRangeParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type CockpitAggregateByDateRangeRow struct {
	TotalReports     int64          `json:"total_reports"`
	TotalSavedHours  pgtype.Numeric `json:"total_saved_hours"`
	TotalAiMinutes   int64          `json:"total_ai_minutes"`
	TotalInnovations int64          `json:"total_innovations"`
	AvgEfficiency    pgtype.Numeric `json:"avg_efficiency"`
}

func (q *Queries) CockpitAggregateByDateRange(ctx context.Context, arg CockpitAggregateByDateRangeParams) (CockpitAggregateByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, cockpitAggregateByDateRange, arg.BotID, arg.StartDate, arg.EndDate)
	var i CockpitAggregateByDateRangeRow
	err := row.Scan(
		&i.TotalReports,
		&i.TotalSavedHours,
		&i.TotalAiMinutes,
		&i.TotalInnovations,
		&i.AvgEfficiency,
	)
	return i, err
}

const cockpitDailyHandExecutionStats = `-- name: CockpitDailyHandExecutionStats :one
SELECT
    COUNT(*)::bigint AS total_executions,
    COUNT(*) FILTER (WHERE status = 'completed')::bigint AS completed_executions,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed_executions
FROM hand_execution_logs
WHERE bot_id = $1
  AND created_at >= $2
  AND created_at < $3
`

type CockpitDailyHandExecutionStatsParams struct {
	BotID    pgtype.UUID        `json:"bot_id"`
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

type CockpitDailyHandExecutionStatsRow struct {
	TotalExecutions     int64 `json:"total_executions"`
	CompletedExecutions int64 `json:"completed_executions"`
	FailedExecutions    int64 `json:"failed_executions"`
}

// Counts hand executions for a bot on a given date.
func (q *Queries) CockpitDailyHandExecutionStats(ctx context.Context, arg CockpitDailyHandExecutionStatsParams) (CockpitDailyHandExecutionStatsRow, error) {
	row := q.db.QueryRow(ctx, cockpitDailyHandExecutionStats, arg.BotID, arg.DayStart, arg.DayEnd)
	var i CockpitDailyHandExecutionStatsRow
	err := row.Scan(&i.TotalExecutions, &i.CompletedExecutions, &i.FailedExecutions)
	return i, err
}

const cockpitDailyMessageStats = `-- name: CockpitDailyMessageStats :one
SELECT
    COUNT(*)::bigint AS message_count,
    COUNT(DISTINCT m.conversation_id)::bigint AS conversation_count
FROM bot_history_messages m
WHERE m.bot_id = $1
  AND m.created_at >= $2
  AND m.created_at < $3
`

type CockpitDailyMessageStatsParams struct {
	BotID    pgtype.UUID        `json:"bot_id"`
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

type CockpitDailyMessageStatsRow struct {
	MessageCount      int64 `json:"message_count"`
	ConversationCount int64 `json:"conversation_count"`
}

// Counts messages and unique conversations for a bot on a given date.
func (q *Queries) CockpitDailyMessageStats(ctx context.Context, arg CockpitDailyMessageStatsParams) (CockpitDailyMessageStatsRow, error) {
	row := q.db.QueryRow(ctx, cockpitDailyMessageStats, arg.BotID, arg.DayStart, arg.DayEnd)
	var i CockpitDailyMessageStatsRow
	err := row.Scan(&i.MessageCount, &i.ConversationCount)
	return i, err
}

const getCockpitConfig = `-- name: GetCockpitConfig :one
SELECT id, key, value, updated_at FROM cockpit_config WHERE key = $1
`

func (q *Queries) GetCockpitConfig(ctx context.Context, key string) (CockpitConfig, error) {
	row := q.db.QueryRow(ctx, getCockpitConfig, key)
	var i CockpitConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const getCockpitDailyReport = `-- name: GetCockpitDailyReport :one
SELECT id, bot_id, user_id, hand_execution_id, report_date, summary, tasks, pending_tasks, total_estimated_saved_hours, total_ai_time_minutes, efficiency_multiplier, innovation_count, created_at FROM cockpit_daily_reports
WHERE bot_id = $1 AND user_id = $2 AND report_date = $3
`

type GetCockpitDailyReportParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	UserID     pgtype.UUID `json:"user_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) GetCockpitDailyReport(ctx context.Context, arg GetCockpitDailyReportParams) (CockpitDailyReport, error) {
	row := q.db.QueryRow(ctx, getCockpitDailyReport, arg.BotID, arg.UserID, arg.ReportDate)
	var i CockpitDailyReport
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.UserID,
		&i.HandExecutionID,
		&i.ReportDate,
		&i.Summary,
		&i.Tasks,
		&i.PendingTasks,
		&i.TotalEstimatedSavedHours,
		&i.TotalAiTimeMinutes,
		&i.EfficiencyMultiplier,
		&i.InnovationCount,
		&i.CreatedAt,
	)
	return i, err
}

const listCockpitConfigs = `-- name: ListCockpitConfigs :many
SELECT id, key, value, updated_at FROM cockpit_config ORDER BY key
`

func (q *Queries) ListCockpitConfigs(ctx context.Context) ([]CockpitConfig, error) {
	rows, err := q.db.Query(ctx, listCockpitConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CockpitConfig
	for rows.Next() {
		var i CockpitConfig
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCockpitDailyReports = `-- name: ListCockpitDailyReports :many
SELECT id, bot_id, user_id, hand_execution_id, report_date, summary, tasks, pending_tasks, total_estimated_saved_hours, total_ai_time_minutes, efficiency_multiplier, innovation_count, created_at FROM cockpit_daily_reports
WHERE bot_id = $1
  AND report_date >= $2
  AND report_date <= $3
ORDER BY report_date DESC
`

type ListCockpitDailyReportsParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListCockpitDailyReports(ctx context.Context, arg ListCockpitDailyReportsParams) ([]CockpitDailyReport, error) {
	rows, err := q.db.Query(ctx, listCockpitDailyReports, arg.BotID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CockpitDailyReport
	for rows.Next() {
		var i CockpitDailyReport
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.UserID,
			&i.HandExecutionID,
			&i.ReportDate,
			&i.Summary,
			&i.Tasks,
			&i.PendingTasks,
			&i.TotalEstimatedSavedHours,
			&i.TotalAiTimeMinutes,
			&i.EfficiencyMultiplier,
			&i.InnovationCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCockpitDailyReportsByUser = `-- name: ListCockpitDailyReportsByUser :many
SELECT id, bot_id, user_id, hand_execution_id, report_date, summary, tasks, pending_tasks, total_estimated_saved_hours, total_ai_time_minutes, efficiency_multiplier, innovation_count, created_at FROM cockpit_daily_reports
WHERE user_id = $1
  AND report_date >= $2
  AND report_date <= $3
ORDER BY report_date DESC
`

type ListCockpitDailyReportsByUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListCockpitDailyReportsByUser(ctx context.Context, arg ListCockpitDailyReportsByUserParams) ([]CockpitDailyReport, error) {
	rows, err := q.db.Query(ctx, listCockpitDailyReportsByUser, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CockpitDailyReport
	for rows.Next() {
		var i CockpitDailyReport
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.UserID,
			&i.HandExecutionID,
			&i.ReportDate,
			&i.Summary,
			&i.Tasks,
			&i.PendingTasks,
			&i.TotalEstimatedSavedHours,
			&i.TotalAiTimeMinutes,
			&i.EfficiencyMultiplier,
			&i.InnovationCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCockpitConfig = `-- name: UpsertCockpitConfig :one
INSERT INTO cockpit_config (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
RETURNING id, key, value, updated_at
`

type UpsertCockpitConfigParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertCockpitConfig(ctx context.Context, arg UpsertCockpitConfigParams) (CockpitConfig, error) {
	row := q.db.QueryRow(ctx, upsertCockpitConfig, arg.Key, arg.Value)
	var i CockpitConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCockpitDailyReport = `-- name: UpsertCockpitDailyReport :one
INSERT INTO cockpit_daily_reports (bot_id, user_id, hand_execution_id, report_date, summary, tasks, pending_tasks, total_estimated_saved_hours, total_ai_time_minutes, efficiency_multiplier, innovation_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (bot_id, user_id, report_date) DO UPDATE SET
    hand_execution_id = $3,
    summary = $5,
    tasks = $6,
    pending_tasks = $7,
    total_estimated_saved_hours = $8,
    total_ai_time_minutes = $9,
    efficiency_multiplier = $10,
    innovation_count = $11
RETURNING id, bot_id, user_id, hand_execution_id, report_date, summary, tasks, pending_tasks, total_estimated_saved_hours, total_ai_time_minutes, efficiency_multiplier, innovation_count, created_at
`

type UpsertCockpitDailyReportParams struct {
	BotID                    pgtype.UUID    `json:"bot_id"`
	UserID                   pgtype.UUID    `json:"user_id"`
	HandExecutionID          pgtype.UUID    `json:"hand_execution_id"`
	ReportDate               pgtype.Date    `json:"report_date"`
	Summary                  string         `json:"summary"`
	Tasks                    []byte         `json:"tasks"`
	PendingTasks             []byte         `json:"pending_tasks"`
	TotalEstimatedSavedHours pgtype.Numeric `json:"total_estimated_saved_hours"`
	TotalAiTimeMinutes       int32          `json:"total_ai_time_minutes"`
	EfficiencyMultiplier     pgtype.Numeric `json:"efficiency_multiplier"`
	InnovationCount          int32          `json:"innovation_count"`
}

func (q *Queries) UpsertCockpitDailyReport(ctx context.Context, arg UpsertCockpitDailyReportParams) (CockpitDailyReport, error) {
	row := q.db.QueryRow(ctx, upsertCockpitDailyReport,
		arg.BotID,
		arg.UserID,
		arg.HandExecutionID,
		arg.ReportDate,
		arg.Summary,
		arg.Tasks,
		arg.PendingTasks,
		arg.TotalEstimatedSavedHours,
		arg.TotalAiTimeMinutes,
		arg.EfficiencyMultiplier,
		arg.InnovationCount,
	)
	var i CockpitDailyReport
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.UserID,
		&i.HandExecutionID,
		&i.ReportDate,
		&i.Summary,
		&i.Tasks,
		&i.PendingTasks,
		&i.TotalEstimatedSavedHours,
		&i.TotalAiTimeMinutes,
		&i.EfficiencyMultiplier,
		&i.InnovationCount,
		&i.CreatedAt,
	)
	return i, err
}
