// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForBatchInsertAuditLogs implements pgx.CopyFromSource.
type iteratorForBatchInsertAuditLogs struct {
	rows                 []BatchInsertAuditLogsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertAuditLogs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertAuditLogs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].BotID,
		r.rows[0].Action,
		r.rows[0].ResourceType,
		r.rows[0].ResourceID,
		r.rows[0].Detail,
		r.rows[0].IpAddress,
		r.rows[0].UserAgent,
	}, nil
}

func (r iteratorForBatchInsertAuditLogs) Err() error {
	return nil
}

func (q *Queries) BatchInsertAuditLogs(ctx context.Context, arg []BatchInsertAuditLogsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"audit_logs"}, []string{"user_id", "bot_id", "action", "resource_type", "resource_id", "detail", "ip_address", "user_agent"}, &iteratorForBatchInsertAuditLogs{rows: arg})
}
