// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cost_tracking.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (scope_type, scope_id, period, limit_amount, alert_threshold, action_on_exceed, is_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, scope_type, scope_id, period, limit_amount, alert_threshold, action_on_exceed, is_enabled, created_at, updated_at
`

type CreateBudgetParams struct {
	ScopeType      string         `json:"scope_type"`
	ScopeID        string         `json:"scope_id"`
	Period         string         `json:"period"`
	LimitAmount    pgtype.Numeric `json:"limit_amount"`
	AlertThreshold pgtype.Numeric `json:"alert_threshold"`
	ActionOnExceed string         `json:"action_on_exceed"`
	IsEnabled      bool           `json:"is_enabled"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.ScopeType,
		arg.ScopeID,
		arg.Period,
		arg.LimitAmount,
		arg.AlertThreshold,
		arg.ActionOnExceed,
		arg.IsEnabled,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitAmount,
		&i.AlertThreshold,
		&i.ActionOnExceed,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, scope_type, scope_id, period, limit_amount, alert_threshold, action_on_exceed, is_enabled, created_at, updated_at FROM budgets
WHERE scope_type = $1 AND scope_id = $2 AND period = $3
`

type GetBudgetParams struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Period    string `json:"period"`
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.ScopeType, arg.ScopeID, arg.Period)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitAmount,
		&i.AlertThreshold,
		&i.ActionOnExceed,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentModelPricing = `-- name: GetCurrentModelPricing :one
SELECT id, model_id, input_price_per_mtok, output_price_per_mtok, cache_read_price_per_mtok, cache_write_price_per_mtok, reasoning_price_per_mtok, effective_from, created_at FROM model_pricing
WHERE model_id = $1 AND effective_from <= now()
ORDER BY effective_from DESC
LIMIT 1
`

func (q *Queries) GetCurrentModelPricing(ctx context.Context, modelID pgtype.UUID) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, getCurrentModelPricing, modelID)
	var i ModelPricing
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputPricePerMtok,
		&i.OutputPricePerMtok,
		&i.CacheReadPricePerMtok,
		&i.CacheWritePricePerMtok,
		&i.ReasoningPricePerMtok,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, scope_type, scope_id, period, limit_amount, alert_threshold, action_on_exceed, is_enabled, created_at, updated_at FROM budgets
WHERE ($1::text IS NULL OR scope_type = $1)
ORDER BY scope_type, scope_id
`

func (q *Queries) ListBudgets(ctx context.Context, scopeType pgtype.Text) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets, scopeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Period,
			&i.LimitAmount,
			&i.AlertThreshold,
			&i.ActionOnExceed,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPricing = `-- name: ListModelPricing :many
SELECT id, model_id, input_price_per_mtok, output_price_per_mtok, cache_read_price_per_mtok, cache_write_price_per_mtok, reasoning_price_per_mtok, effective_from, created_at FROM model_pricing
WHERE model_id = $1
ORDER BY effective_from DESC
`

func (q *Queries) ListModelPricing(ctx context.Context, modelID pgtype.UUID) ([]ModelPricing, error) {
	rows, err := q.db.Query(ctx, listModelPricing, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPricing
	for rows.Next() {
		var i ModelPricing
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.InputPricePerMtok,
			&i.OutputPricePerMtok,
			&i.CacheReadPricePerMtok,
			&i.CacheWritePricePerMtok,
			&i.ReasoningPricePerMtok,
			&i.EffectiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET limit_amount = $2, alert_threshold = $3, action_on_exceed = $4, is_enabled = $5, updated_at = now()
WHERE id = $1
RETURNING id, scope_type, scope_id, period, limit_amount, alert_threshold, action_on_exceed, is_enabled, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID             pgtype.UUID    `json:"id"`
	LimitAmount    pgtype.Numeric `json:"limit_amount"`
	AlertThreshold pgtype.Numeric `json:"alert_threshold"`
	ActionOnExceed string         `json:"action_on_exceed"`
	IsEnabled      bool           `json:"is_enabled"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.LimitAmount,
		arg.AlertThreshold,
		arg.ActionOnExceed,
		arg.IsEnabled,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitAmount,
		&i.AlertThreshold,
		&i.ActionOnExceed,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertModelPricing = `-- name: UpsertModelPricing :one
INSERT INTO model_pricing (model_id, input_price_per_mtok, output_price_per_mtok, cache_read_price_per_mtok, cache_write_price_per_mtok, reasoning_price_per_mtok, effective_from)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (model_id, effective_from) DO UPDATE SET
    input_price_per_mtok = $2,
    output_price_per_mtok = $3,
    cache_read_price_per_mtok = $4,
    cache_write_price_per_mtok = $5,
    reasoning_price_per_mtok = $6
RETURNING id, model_id, input_price_per_mtok, output_price_per_mtok, cache_read_price_per_mtok, cache_write_price_per_mtok, reasoning_price_per_mtok, effective_from, created_at
`

type UpsertModelPricingParams struct {
	ModelID                pgtype.UUID        `json:"model_id"`
	InputPricePerMtok      pgtype.Numeric     `json:"input_price_per_mtok"`
	OutputPricePerMtok     pgtype.Numeric     `json:"output_price_per_mtok"`
	CacheReadPricePerMtok  pgtype.Numeric     `json:"cache_read_price_per_mtok"`
	CacheWritePricePerMtok pgtype.Numeric     `json:"cache_write_price_per_mtok"`
	ReasoningPricePerMtok  pgtype.Numeric     `json:"reasoning_price_per_mtok"`
	EffectiveFrom          pgtype.Timestamptz `json:"effective_from"`
}

func (q *Queries) UpsertModelPricing(ctx context.Context, arg UpsertModelPricingParams) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, upsertModelPricing,
		arg.ModelID,
		arg.InputPricePerMtok,
		arg.OutputPricePerMtok,
		arg.CacheReadPricePerMtok,
		arg.CacheWritePricePerMtok,
		arg.ReasoningPricePerMtok,
		arg.EffectiveFrom,
	)
	var i ModelPricing
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.InputPricePerMtok,
		&i.OutputPricePerMtok,
		&i.CacheReadPricePerMtok,
		&i.CacheWritePricePerMtok,
		&i.ReasoningPricePerMtok,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}
