// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDepartmentMember = `-- name: AddDepartmentMember :exec
INSERT INTO department_members (department_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (department_id, user_id) DO UPDATE SET role = $3
`

type AddDepartmentMemberParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Role         string      `json:"role"`
}

func (q *Queries) AddDepartmentMember(ctx context.Context, arg AddDepartmentMemberParams) error {
	_, err := q.db.Exec(ctx, addDepartmentMember, arg.DepartmentID, arg.UserID, arg.Role)
	return err
}

const checkBotDepartmentAccess = `-- name: CheckBotDepartmentAccess :one
SELECT EXISTS(
    SELECT 1 FROM bot_department_access
    WHERE bot_id = $1 AND department_id = $2
) AS has_access
`

type CheckBotDepartmentAccessParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) CheckBotDepartmentAccess(ctx context.Context, arg CheckBotDepartmentAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBotDepartmentAccess, arg.BotID, arg.DepartmentID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const checkUserDepartmentMembership = `-- name: CheckUserDepartmentMembership :one
SELECT EXISTS(
    SELECT 1 FROM department_members
    WHERE department_id = $1 AND user_id = $2
) AS is_member
`

type CheckUserDepartmentMembershipParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckUserDepartmentMembership(ctx context.Context, arg CheckUserDepartmentMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserDepartmentMembership, arg.DepartmentID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, description, parent_id, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, parent_id, metadata, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.Metadata,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, description, parent_id, metadata, created_at, updated_at FROM departments WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByName = `-- name: GetDepartmentByName :one
SELECT id, name, description, parent_id, metadata, created_at, updated_at FROM departments WHERE name = $1
`

func (q *Queries) GetDepartmentByName(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByName, name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotDepartments = `-- name: ListBotDepartments :many
SELECT d.id, d.name, d.description, d.parent_id, d.metadata, d.created_at, d.updated_at
FROM departments d
JOIN bot_department_access bda ON bda.department_id = d.id
WHERE bda.bot_id = $1
ORDER BY d.name
`

func (q *Queries) ListBotDepartments(ctx context.Context, botID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listBotDepartments, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildDepartments = `-- name: ListChildDepartments :many
SELECT id, name, description, parent_id, metadata, created_at, updated_at FROM departments WHERE parent_id = $1 ORDER BY name
`

func (q *Queries) ListChildDepartments(ctx context.Context, parentID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listChildDepartments, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartmentBots = `-- name: ListDepartmentBots :many
SELECT b.id, b.owner_user_id, b.type, b.display_name, b.avatar_url, b.is_active, b.status, b.metadata, b.created_at, b.updated_at
FROM bots b
JOIN bot_department_access bda ON bda.bot_id = b.id
WHERE bda.department_id = $1
ORDER BY b.display_name
`

type ListDepartmentBotsRow struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Type        string             `json:"type"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsActive    bool               `json:"is_active"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDepartmentBots(ctx context.Context, departmentID pgtype.UUID) ([]ListDepartmentBotsRow, error) {
	rows, err := q.db.Query(ctx, listDepartmentBots, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepartmentBotsRow
	for rows.Next() {
		var i ListDepartmentBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Type,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartmentMembers = `-- name: ListDepartmentMembers :many
SELECT dm.department_id, dm.user_id, dm.role, dm.created_at, u.username, u.display_name, u.role AS user_role
FROM department_members dm
JOIN users u ON u.id = dm.user_id
WHERE dm.department_id = $1
ORDER BY dm.created_at
`

type ListDepartmentMembersRow struct {
	DepartmentID pgtype.UUID        `json:"department_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Username     pgtype.Text        `json:"username"`
	DisplayName  pgtype.Text        `json:"display_name"`
	UserRole     string             `json:"user_role"`
}

func (q *Queries) ListDepartmentMembers(ctx context.Context, departmentID pgtype.UUID) ([]ListDepartmentMembersRow, error) {
	rows, err := q.db.Query(ctx, listDepartmentMembers, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepartmentMembersRow
	for rows.Next() {
		var i ListDepartmentMembersRow
		if err := rows.Scan(
			&i.DepartmentID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, description, parent_id, metadata, created_at, updated_at FROM departments ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDepartments = `-- name: ListUserDepartments :many
SELECT d.id, d.name, d.description, d.parent_id, d.metadata, d.created_at, d.updated_at, dm.role AS member_role
FROM departments d
JOIN department_members dm ON dm.department_id = d.id
WHERE dm.user_id = $1
ORDER BY d.name
`

type ListUserDepartmentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberRole  string             `json:"member_role"`
}

func (q *Queries) ListUserDepartments(ctx context.Context, userID pgtype.UUID) ([]ListUserDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listUserDepartments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDepartmentsRow
	for rows.Next() {
		var i ListUserDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBotDepartmentAccess = `-- name: RemoveBotDepartmentAccess :exec
DELETE FROM bot_department_access WHERE bot_id = $1 AND department_id = $2
`

type RemoveBotDepartmentAccessParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) RemoveBotDepartmentAccess(ctx context.Context, arg RemoveBotDepartmentAccessParams) error {
	_, err := q.db.Exec(ctx, removeBotDepartmentAccess, arg.BotID, arg.DepartmentID)
	return err
}

const removeDepartmentMember = `-- name: RemoveDepartmentMember :exec
DELETE FROM department_members WHERE department_id = $1 AND user_id = $2
`

type RemoveDepartmentMemberParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveDepartmentMember(ctx context.Context, arg RemoveDepartmentMemberParams) error {
	_, err := q.db.Exec(ctx, removeDepartmentMember, arg.DepartmentID, arg.UserID)
	return err
}

const setBotDepartmentAccess = `-- name: SetBotDepartmentAccess :exec
INSERT INTO bot_department_access (bot_id, department_id)
VALUES ($1, $2)
ON CONFLICT (bot_id, department_id) DO NOTHING
`

type SetBotDepartmentAccessParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) SetBotDepartmentAccess(ctx context.Context, arg SetBotDepartmentAccessParams) error {
	_, err := q.db.Exec(ctx, setBotDepartmentAccess, arg.BotID, arg.DepartmentID)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2, description = $3, parent_id = $4, metadata = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, description, parent_id, metadata, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.Metadata,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
