// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: hands.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHand = `-- name: CreateHand :one
INSERT INTO hands (bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata, created_at, updated_at
`

type CreateHandParams struct {
	BotID            pgtype.UUID `json:"bot_id"`
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	Content          string      `json:"content"`
	Type             string      `json:"type"`
	SchedulePattern  pgtype.Text `json:"schedule_pattern"`
	ScheduleTimezone pgtype.Text `json:"schedule_timezone"`
	ScheduleMaxCalls pgtype.Int4 `json:"schedule_max_calls"`
	Triggers         []byte      `json:"triggers"`
	AllowedTools     []byte      `json:"allowed_tools"`
	ModelConfig      []byte      `json:"model_config"`
	OutputConfig     []byte      `json:"output_config"`
	Permissions      []byte      `json:"permissions"`
	IsEnabled        bool        `json:"is_enabled"`
	Metadata         []byte      `json:"metadata"`
}

func (q *Queries) CreateHand(ctx context.Context, arg CreateHandParams) (Hand, error) {
	row := q.db.QueryRow(ctx, createHand,
		arg.BotID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Type,
		arg.SchedulePattern,
		arg.ScheduleTimezone,
		arg.ScheduleMaxCalls,
		arg.Triggers,
		arg.AllowedTools,
		arg.ModelConfig,
		arg.OutputConfig,
		arg.Permissions,
		arg.IsEnabled,
		arg.Metadata,
	)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Type,
		&i.SchedulePattern,
		&i.ScheduleTimezone,
		&i.ScheduleMaxCalls,
		&i.Triggers,
		&i.AllowedTools,
		&i.ModelConfig,
		&i.OutputConfig,
		&i.Permissions,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHandExecutionLog = `-- name: CreateHandExecutionLog :one
INSERT INTO hand_execution_logs (hand_id, bot_id, trigger_type, trigger_detail, status, model_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, hand_id, bot_id, trigger_type, trigger_detail, status, result_text, error_message, usage, model_id, started_at, completed_at, created_at
`

type CreateHandExecutionLogParams struct {
	HandID        pgtype.UUID `json:"hand_id"`
	BotID         pgtype.UUID `json:"bot_id"`
	TriggerType   string      `json:"trigger_type"`
	TriggerDetail []byte      `json:"trigger_detail"`
	Status        string      `json:"status"`
	ModelID       pgtype.UUID `json:"model_id"`
}

func (q *Queries) CreateHandExecutionLog(ctx context.Context, arg CreateHandExecutionLogParams) (HandExecutionLog, error) {
	row := q.db.QueryRow(ctx, createHandExecutionLog,
		arg.HandID,
		arg.BotID,
		arg.TriggerType,
		arg.TriggerDetail,
		arg.Status,
		arg.ModelID,
	)
	var i HandExecutionLog
	err := row.Scan(
		&i.ID,
		&i.HandID,
		&i.BotID,
		&i.TriggerType,
		&i.TriggerDetail,
		&i.Status,
		&i.ResultText,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHand = `-- name: DeleteHand :exec
DELETE FROM hands WHERE id = $1
`

func (q *Queries) DeleteHand(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHand, id)
	return err
}

const getHandByID = `-- name: GetHandByID :one
SELECT id, bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata, created_at, updated_at FROM hands WHERE id = $1
`

func (q *Queries) GetHandByID(ctx context.Context, id pgtype.UUID) (Hand, error) {
	row := q.db.QueryRow(ctx, getHandByID, id)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Type,
		&i.SchedulePattern,
		&i.ScheduleTimezone,
		&i.ScheduleMaxCalls,
		&i.Triggers,
		&i.AllowedTools,
		&i.ModelConfig,
		&i.OutputConfig,
		&i.Permissions,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHandByName = `-- name: GetHandByName :one
SELECT id, bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata, created_at, updated_at FROM hands WHERE bot_id = $1 AND name = $2
`

type GetHandByNameParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Name  string      `json:"name"`
}

func (q *Queries) GetHandByName(ctx context.Context, arg GetHandByNameParams) (Hand, error) {
	row := q.db.QueryRow(ctx, getHandByName, arg.BotID, arg.Name)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Type,
		&i.SchedulePattern,
		&i.ScheduleTimezone,
		&i.ScheduleMaxCalls,
		&i.Triggers,
		&i.AllowedTools,
		&i.ModelConfig,
		&i.OutputConfig,
		&i.Permissions,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHandExecutionLog = `-- name: GetHandExecutionLog :one
SELECT id, hand_id, bot_id, trigger_type, trigger_detail, status, result_text, error_message, usage, model_id, started_at, completed_at, created_at FROM hand_execution_logs WHERE id = $1
`

func (q *Queries) GetHandExecutionLog(ctx context.Context, id pgtype.UUID) (HandExecutionLog, error) {
	row := q.db.QueryRow(ctx, getHandExecutionLog, id)
	var i HandExecutionLog
	err := row.Scan(
		&i.ID,
		&i.HandID,
		&i.BotID,
		&i.TriggerType,
		&i.TriggerDetail,
		&i.Status,
		&i.ResultText,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledHands = `-- name: ListEnabledHands :many
SELECT id, bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata, created_at, updated_at FROM hands
WHERE bot_id = $1 AND is_enabled = true
ORDER BY name
`

func (q *Queries) ListEnabledHands(ctx context.Context, botID pgtype.UUID) ([]Hand, error) {
	rows, err := q.db.Query(ctx, listEnabledHands, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hand
	for rows.Next() {
		var i Hand
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.Type,
			&i.SchedulePattern,
			&i.ScheduleTimezone,
			&i.ScheduleMaxCalls,
			&i.Triggers,
			&i.AllowedTools,
			&i.ModelConfig,
			&i.OutputConfig,
			&i.Permissions,
			&i.IsEnabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandExecutionLogs = `-- name: ListHandExecutionLogs :many
SELECT id, hand_id, bot_id, trigger_type, trigger_detail, status, result_text, error_message, usage, model_id, started_at, completed_at, created_at FROM hand_execution_logs
WHERE hand_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHandExecutionLogsParams struct {
	HandID pgtype.UUID `json:"hand_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListHandExecutionLogs(ctx context.Context, arg ListHandExecutionLogsParams) ([]HandExecutionLog, error) {
	rows, err := q.db.Query(ctx, listHandExecutionLogs, arg.HandID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandExecutionLog
	for rows.Next() {
		var i HandExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.HandID,
			&i.BotID,
			&i.TriggerType,
			&i.TriggerDetail,
			&i.Status,
			&i.ResultText,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHands = `-- name: ListHands :many
SELECT id, bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata, created_at, updated_at FROM hands
WHERE bot_id = $1
ORDER BY name
`

func (q *Queries) ListHands(ctx context.Context, botID pgtype.UUID) ([]Hand, error) {
	rows, err := q.db.Query(ctx, listHands, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hand
	for rows.Next() {
		var i Hand
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.Type,
			&i.SchedulePattern,
			&i.ScheduleTimezone,
			&i.ScheduleMaxCalls,
			&i.Triggers,
			&i.AllowedTools,
			&i.ModelConfig,
			&i.OutputConfig,
			&i.Permissions,
			&i.IsEnabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHand = `-- name: UpdateHand :one
UPDATE hands
SET name = $2, description = $3, content = $4, type = $5,
    schedule_pattern = $6, schedule_timezone = $7, schedule_max_calls = $8,
    triggers = $9, allowed_tools = $10, model_config = $11, output_config = $12,
    permissions = $13, is_enabled = $14, metadata = $15, updated_at = now()
WHERE id = $1
RETURNING id, bot_id, name, description, content, type, schedule_pattern, schedule_timezone, schedule_max_calls, triggers, allowed_tools, model_config, output_config, permissions, is_enabled, metadata, created_at, updated_at
`

type UpdateHandParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	Content          string      `json:"content"`
	Type             string      `json:"type"`
	SchedulePattern  pgtype.Text `json:"schedule_pattern"`
	ScheduleTimezone pgtype.Text `json:"schedule_timezone"`
	ScheduleMaxCalls pgtype.Int4 `json:"schedule_max_calls"`
	Triggers         []byte      `json:"triggers"`
	AllowedTools     []byte      `json:"allowed_tools"`
	ModelConfig      []byte      `json:"model_config"`
	OutputConfig     []byte      `json:"output_config"`
	Permissions      []byte      `json:"permissions"`
	IsEnabled        bool        `json:"is_enabled"`
	Metadata         []byte      `json:"metadata"`
}

func (q *Queries) UpdateHand(ctx context.Context, arg UpdateHandParams) (Hand, error) {
	row := q.db.QueryRow(ctx, updateHand,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Type,
		arg.SchedulePattern,
		arg.ScheduleTimezone,
		arg.ScheduleMaxCalls,
		arg.Triggers,
		arg.AllowedTools,
		arg.ModelConfig,
		arg.OutputConfig,
		arg.Permissions,
		arg.IsEnabled,
		arg.Metadata,
	)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Type,
		&i.SchedulePattern,
		&i.ScheduleTimezone,
		&i.ScheduleMaxCalls,
		&i.Triggers,
		&i.AllowedTools,
		&i.ModelConfig,
		&i.OutputConfig,
		&i.Permissions,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHandExecutionLog = `-- name: UpdateHandExecutionLog :one
UPDATE hand_execution_logs
SET status = $2, result_text = $3, error_message = $4, usage = $5, completed_at = $6
WHERE id = $1
RETURNING id, hand_id, bot_id, trigger_type, trigger_detail, status, result_text, error_message, usage, model_id, started_at, completed_at, created_at
`

type UpdateHandExecutionLogParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	ResultText   pgtype.Text        `json:"result_text"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Usage        []byte             `json:"usage"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateHandExecutionLog(ctx context.Context, arg UpdateHandExecutionLogParams) (HandExecutionLog, error) {
	row := q.db.QueryRow(ctx, updateHandExecutionLog,
		arg.ID,
		arg.Status,
		arg.ResultText,
		arg.ErrorMessage,
		arg.Usage,
		arg.CompletedAt,
	)
	var i HandExecutionLog
	err := row.Scan(
		&i.ID,
		&i.HandID,
		&i.BotID,
		&i.TriggerType,
		&i.TriggerDetail,
		&i.Status,
		&i.ResultText,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
