// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_routing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModelRoute = `-- name: CreateModelRoute :one
INSERT INTO bot_model_routes (bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata, created_at, updated_at
`

type CreateModelRouteParams struct {
	BotID          pgtype.UUID `json:"bot_id"`
	Name           string      `json:"name"`
	ModelID        pgtype.UUID `json:"model_id"`
	Priority       int32       `json:"priority"`
	ComplexityTier string      `json:"complexity_tier"`
	IsEnabled      bool        `json:"is_enabled"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateModelRoute(ctx context.Context, arg CreateModelRouteParams) (BotModelRoute, error) {
	row := q.db.QueryRow(ctx, createModelRoute,
		arg.BotID,
		arg.Name,
		arg.ModelID,
		arg.Priority,
		arg.ComplexityTier,
		arg.IsEnabled,
		arg.Metadata,
	)
	var i BotModelRoute
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.ModelID,
		&i.Priority,
		&i.ComplexityTier,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteModelRoute = `-- name: DeleteModelRoute :exec
DELETE FROM bot_model_routes WHERE id = $1
`

func (q *Queries) DeleteModelRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteModelRoute, id)
	return err
}

const getModelRouteByID = `-- name: GetModelRouteByID :one
SELECT id, bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata, created_at, updated_at FROM bot_model_routes WHERE id = $1
`

func (q *Queries) GetModelRouteByID(ctx context.Context, id pgtype.UUID) (BotModelRoute, error) {
	row := q.db.QueryRow(ctx, getModelRouteByID, id)
	var i BotModelRoute
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.ModelID,
		&i.Priority,
		&i.ComplexityTier,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelRouteByTier = `-- name: GetModelRouteByTier :one
SELECT id, bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata, created_at, updated_at FROM bot_model_routes
WHERE bot_id = $1 AND complexity_tier = $2 AND is_enabled = true
ORDER BY priority DESC
LIMIT 1
`

type GetModelRouteByTierParams struct {
	BotID          pgtype.UUID `json:"bot_id"`
	ComplexityTier string      `json:"complexity_tier"`
}

func (q *Queries) GetModelRouteByTier(ctx context.Context, arg GetModelRouteByTierParams) (BotModelRoute, error) {
	row := q.db.QueryRow(ctx, getModelRouteByTier, arg.BotID, arg.ComplexityTier)
	var i BotModelRoute
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.ModelID,
		&i.Priority,
		&i.ComplexityTier,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledModelRoutes = `-- name: ListEnabledModelRoutes :many
SELECT id, bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata, created_at, updated_at FROM bot_model_routes
WHERE bot_id = $1 AND is_enabled = true
ORDER BY priority DESC
`

func (q *Queries) ListEnabledModelRoutes(ctx context.Context, botID pgtype.UUID) ([]BotModelRoute, error) {
	rows, err := q.db.Query(ctx, listEnabledModelRoutes, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotModelRoute
	for rows.Next() {
		var i BotModelRoute
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Name,
			&i.ModelID,
			&i.Priority,
			&i.ComplexityTier,
			&i.IsEnabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelRoutes = `-- name: ListModelRoutes :many
SELECT id, bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata, created_at, updated_at FROM bot_model_routes
WHERE bot_id = $1
ORDER BY priority DESC, name
`

func (q *Queries) ListModelRoutes(ctx context.Context, botID pgtype.UUID) ([]BotModelRoute, error) {
	rows, err := q.db.Query(ctx, listModelRoutes, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotModelRoute
	for rows.Next() {
		var i BotModelRoute
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Name,
			&i.ModelID,
			&i.Priority,
			&i.ComplexityTier,
			&i.IsEnabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelRoute = `-- name: UpdateModelRoute :one
UPDATE bot_model_routes
SET name = $2, model_id = $3, priority = $4, complexity_tier = $5, is_enabled = $6, metadata = $7, updated_at = now()
WHERE id = $1
RETURNING id, bot_id, name, model_id, priority, complexity_tier, is_enabled, metadata, created_at, updated_at
`

type UpdateModelRouteParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	ModelID        pgtype.UUID `json:"model_id"`
	Priority       int32       `json:"priority"`
	ComplexityTier string      `json:"complexity_tier"`
	IsEnabled      bool        `json:"is_enabled"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) UpdateModelRoute(ctx context.Context, arg UpdateModelRouteParams) (BotModelRoute, error) {
	row := q.db.QueryRow(ctx, updateModelRoute,
		arg.ID,
		arg.Name,
		arg.ModelID,
		arg.Priority,
		arg.ComplexityTier,
		arg.IsEnabled,
		arg.Metadata,
	)
	var i BotModelRoute
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.ModelID,
		&i.Priority,
		&i.ComplexityTier,
		&i.IsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
