// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: skill_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSkillTemplates = `-- name: CountSkillTemplates :one
SELECT count(*) FROM skill_templates
`

func (q *Queries) CountSkillTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSkillTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBotSkillInstall = `-- name: CreateBotSkillInstall :one
INSERT INTO bot_skill_installs (
  bot_id, template_id, installed_version, skill_name
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, bot_id, template_id, installed_version, skill_name, customized, created_at, updated_at
`

type CreateBotSkillInstallParams struct {
	BotID            pgtype.UUID `json:"bot_id"`
	TemplateID       pgtype.UUID `json:"template_id"`
	InstalledVersion int32       `json:"installed_version"`
	SkillName        string      `json:"skill_name"`
}

func (q *Queries) CreateBotSkillInstall(ctx context.Context, arg CreateBotSkillInstallParams) (BotSkillInstall, error) {
	row := q.db.QueryRow(ctx, createBotSkillInstall,
		arg.BotID,
		arg.TemplateID,
		arg.InstalledVersion,
		arg.SkillName,
	)
	var i BotSkillInstall
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.TemplateID,
		&i.InstalledVersion,
		&i.SkillName,
		&i.Customized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkillTemplate = `-- name: CreateSkillTemplate :one
INSERT INTO skill_templates (
  name, slug, description, category, content, author, icon, tags, is_published
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at
`

type CreateSkillTemplateParams struct {
	Name        string   `json:"name"`
	Slug        string   `json:"slug"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Content     string   `json:"content"`
	Author      string   `json:"author"`
	Icon        string   `json:"icon"`
	Tags        []string `json:"tags"`
	IsPublished bool     `json:"is_published"`
}

func (q *Queries) CreateSkillTemplate(ctx context.Context, arg CreateSkillTemplateParams) (SkillTemplate, error) {
	row := q.db.QueryRow(ctx, createSkillTemplate,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Author,
		arg.Icon,
		arg.Tags,
		arg.IsPublished,
	)
	var i SkillTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.Author,
		&i.Icon,
		&i.Tags,
		&i.IsPublished,
		&i.InstallCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementInstallCount = `-- name: DecrementInstallCount :exec
UPDATE skill_templates SET install_count = GREATEST(install_count - 1, 0), updated_at = now() WHERE id = $1
`

func (q *Queries) DecrementInstallCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementInstallCount, id)
	return err
}

const deleteBotSkillInstall = `-- name: DeleteBotSkillInstall :exec
DELETE FROM bot_skill_installs WHERE bot_id = $1 AND template_id = $2
`

type DeleteBotSkillInstallParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	TemplateID pgtype.UUID `json:"template_id"`
}

func (q *Queries) DeleteBotSkillInstall(ctx context.Context, arg DeleteBotSkillInstallParams) error {
	_, err := q.db.Exec(ctx, deleteBotSkillInstall, arg.BotID, arg.TemplateID)
	return err
}

const deleteSkillTemplate = `-- name: DeleteSkillTemplate :exec
DELETE FROM skill_templates WHERE id = $1
`

func (q *Queries) DeleteSkillTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillTemplate, id)
	return err
}

const getBotSkillInstall = `-- name: GetBotSkillInstall :one
SELECT id, bot_id, template_id, installed_version, skill_name, customized, created_at, updated_at FROM bot_skill_installs WHERE bot_id = $1 AND template_id = $2
`

type GetBotSkillInstallParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	TemplateID pgtype.UUID `json:"template_id"`
}

func (q *Queries) GetBotSkillInstall(ctx context.Context, arg GetBotSkillInstallParams) (BotSkillInstall, error) {
	row := q.db.QueryRow(ctx, getBotSkillInstall, arg.BotID, arg.TemplateID)
	var i BotSkillInstall
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.TemplateID,
		&i.InstalledVersion,
		&i.SkillName,
		&i.Customized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotSkillInstallBySkillName = `-- name: GetBotSkillInstallBySkillName :one
SELECT id, bot_id, template_id, installed_version, skill_name, customized, created_at, updated_at FROM bot_skill_installs WHERE bot_id = $1 AND skill_name = $2
`

type GetBotSkillInstallBySkillNameParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SkillName string      `json:"skill_name"`
}

func (q *Queries) GetBotSkillInstallBySkillName(ctx context.Context, arg GetBotSkillInstallBySkillNameParams) (BotSkillInstall, error) {
	row := q.db.QueryRow(ctx, getBotSkillInstallBySkillName, arg.BotID, arg.SkillName)
	var i BotSkillInstall
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.TemplateID,
		&i.InstalledVersion,
		&i.SkillName,
		&i.Customized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillTemplateByID = `-- name: GetSkillTemplateByID :one
SELECT id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at FROM skill_templates WHERE id = $1
`

func (q *Queries) GetSkillTemplateByID(ctx context.Context, id pgtype.UUID) (SkillTemplate, error) {
	row := q.db.QueryRow(ctx, getSkillTemplateByID, id)
	var i SkillTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.Author,
		&i.Icon,
		&i.Tags,
		&i.IsPublished,
		&i.InstallCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillTemplateBySlug = `-- name: GetSkillTemplateBySlug :one
SELECT id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at FROM skill_templates WHERE slug = $1
`

func (q *Queries) GetSkillTemplateBySlug(ctx context.Context, slug string) (SkillTemplate, error) {
	row := q.db.QueryRow(ctx, getSkillTemplateBySlug, slug)
	var i SkillTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.Author,
		&i.Icon,
		&i.Tags,
		&i.IsPublished,
		&i.InstallCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInstallCount = `-- name: IncrementInstallCount :exec
UPDATE skill_templates SET install_count = install_count + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementInstallCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementInstallCount, id)
	return err
}

const listBotSkillInstalls = `-- name: ListBotSkillInstalls :many
SELECT
  bsi.id, bsi.bot_id, bsi.template_id, bsi.installed_version, bsi.skill_name, bsi.customized, bsi.created_at, bsi.updated_at,
  st.version AS latest_version,
  st.name AS template_name
FROM bot_skill_installs bsi
LEFT JOIN skill_templates st ON st.id = bsi.template_id
WHERE bsi.bot_id = $1
ORDER BY bsi.created_at DESC
`

type ListBotSkillInstallsRow struct {
	ID               pgtype.UUID        `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	TemplateID       pgtype.UUID        `json:"template_id"`
	InstalledVersion int32              `json:"installed_version"`
	SkillName        string             `json:"skill_name"`
	Customized       bool               `json:"customized"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LatestVersion    pgtype.Int4        `json:"latest_version"`
	TemplateName     pgtype.Text        `json:"template_name"`
}

func (q *Queries) ListBotSkillInstalls(ctx context.Context, botID pgtype.UUID) ([]ListBotSkillInstallsRow, error) {
	rows, err := q.db.Query(ctx, listBotSkillInstalls, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotSkillInstallsRow
	for rows.Next() {
		var i ListBotSkillInstallsRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.TemplateID,
			&i.InstalledVersion,
			&i.SkillName,
			&i.Customized,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersion,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSkillTemplates = `-- name: ListPublishedSkillTemplates :many
SELECT id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at FROM skill_templates WHERE is_published = true ORDER BY install_count DESC, created_at DESC
`

func (q *Queries) ListPublishedSkillTemplates(ctx context.Context) ([]SkillTemplate, error) {
	rows, err := q.db.Query(ctx, listPublishedSkillTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillTemplate
	for rows.Next() {
		var i SkillTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.Author,
			&i.Icon,
			&i.Tags,
			&i.IsPublished,
			&i.InstallCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillTemplates = `-- name: ListSkillTemplates :many
SELECT id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at FROM skill_templates ORDER BY install_count DESC, created_at DESC
`

func (q *Queries) ListSkillTemplates(ctx context.Context) ([]SkillTemplate, error) {
	rows, err := q.db.Query(ctx, listSkillTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillTemplate
	for rows.Next() {
		var i SkillTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.Author,
			&i.Icon,
			&i.Tags,
			&i.IsPublished,
			&i.InstallCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillTemplatesByCategory = `-- name: ListSkillTemplatesByCategory :many
SELECT id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at FROM skill_templates WHERE is_published = true AND category = $1 ORDER BY install_count DESC, created_at DESC
`

func (q *Queries) ListSkillTemplatesByCategory(ctx context.Context, category string) ([]SkillTemplate, error) {
	rows, err := q.db.Query(ctx, listSkillTemplatesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillTemplate
	for rows.Next() {
		var i SkillTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.Author,
			&i.Icon,
			&i.Tags,
			&i.IsPublished,
			&i.InstallCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBotSkillCustomized = `-- name: MarkBotSkillCustomized :exec
UPDATE bot_skill_installs
SET customized = true, updated_at = now()
WHERE bot_id = $1 AND skill_name = $2
`

type MarkBotSkillCustomizedParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SkillName string      `json:"skill_name"`
}

func (q *Queries) MarkBotSkillCustomized(ctx context.Context, arg MarkBotSkillCustomizedParams) error {
	_, err := q.db.Exec(ctx, markBotSkillCustomized, arg.BotID, arg.SkillName)
	return err
}

const updateBotSkillInstallVersion = `-- name: UpdateBotSkillInstallVersion :one
UPDATE bot_skill_installs
SET installed_version = $1, customized = false, updated_at = now()
WHERE bot_id = $2 AND template_id = $3
RETURNING id, bot_id, template_id, installed_version, skill_name, customized, created_at, updated_at
`

type UpdateBotSkillInstallVersionParams struct {
	InstalledVersion int32       `json:"installed_version"`
	BotID            pgtype.UUID `json:"bot_id"`
	TemplateID       pgtype.UUID `json:"template_id"`
}

func (q *Queries) UpdateBotSkillInstallVersion(ctx context.Context, arg UpdateBotSkillInstallVersionParams) (BotSkillInstall, error) {
	row := q.db.QueryRow(ctx, updateBotSkillInstallVersion, arg.InstalledVersion, arg.BotID, arg.TemplateID)
	var i BotSkillInstall
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.TemplateID,
		&i.InstalledVersion,
		&i.SkillName,
		&i.Customized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkillTemplate = `-- name: UpdateSkillTemplate :one
UPDATE skill_templates
SET
  name = $1,
  slug = $2,
  description = $3,
  category = $4,
  content = $5,
  author = $6,
  icon = $7,
  tags = $8,
  is_published = $9,
  version = version + 1,
  updated_at = now()
WHERE id = $10
RETURNING id, name, slug, description, category, content, version, author, icon, tags, is_published, install_count, created_at, updated_at
`

type UpdateSkillTemplateParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Author      string      `json:"author"`
	Icon        string      `json:"icon"`
	Tags        []string    `json:"tags"`
	IsPublished bool        `json:"is_published"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSkillTemplate(ctx context.Context, arg UpdateSkillTemplateParams) (SkillTemplate, error) {
	row := q.db.QueryRow(ctx, updateSkillTemplate,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Author,
		arg.Icon,
		arg.Tags,
		arg.IsPublished,
		arg.ID,
	)
	var i SkillTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.Author,
		&i.Icon,
		&i.Tags,
		&i.IsPublished,
		&i.InstallCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
