// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus():Promise<Record<string, any>>;

export function LoginWithPassword(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
