// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

type AppStatus = Record<string, unknown>;

type AppLoginResponse = AppStatus & {
	access_token?: string;
	bot_name?: string;
	hostname?: string;
};

export function GetStatus(): Promise<AppStatus>;

export function LoginWithPassword(arg1: string, arg2: string, arg3: string): Promise<AppLoginResponse>;
