// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoginWithPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginWithPassword'](arg1, arg2, arg3);
}
